name: "Qinhu Wang | 王秦虎"
markdown: redcarpet
pygments: true
pygments: true
permalink: /:title

author: "Qinhu Wang"
atom-baseurl: "http://wangqinhu.com"

github:  wangqinhu
twitter: wangqinhu
disqus:  wangqinhu
rms:     8tuhaxyvvqh

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

exclude: [README.md]
