title:            Time & Stuff
tagline:          wangqinhu
description:      Qinhu Wang | 王秦虎

# URL
url:              http://wangqinhu.com

# Owner/author information
owner:
  name:           Wang Qinhu
  avatar:         bio-photo.jpg
  bio:            "PhD student at NWAFU"
  email:          qinhu.wang@gmail.com
  twitter:        wangqinhu
  github:         wangqinhu

# Google
  google_analytics: UA-20201961-3


# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Posts
    url: /posts/
  - title: Message
    url: /message/
  - title: About
    url: /about/
  - title: GeneHouse
    url: /genehouse/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Shanghai
future:      true
pygments:    true
markdown:    redcarpet

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:title/

include: [".htaccess"]
