name: "Qinhu Wang | 王秦虎"
markdown: redcarpet
pygments: true
pygments: true
permalink: /:title

author: "Qinhu Wang"
atom-baseurl: "http://wangqinhu.com"

github:  wangqinhu
twitter: wangqinhu
disqus:  wangqinhu

navigations:
  - title: Home |  首页
    class: fa fa-home
    href: /
  - title: Archive | 文档
    class: fa fa-list-ul
    href: /archive.html
  - title: About | 关于
    class: fa fa-user
    href: /about.html
  - title: Tags | 标签
    class: fa fa-tags
    href: /tags.html
  - title: Subscribe | 订阅
    class: fa fa-rss
    href: /atom.xml

exclude: [README.md]
